### PR TITLE
Fixing Response Validation + removal of ommitted additional headers

### PR DESCRIPTION
**Pull request by nickveenhof**
Response validation was not using the right hash_hmac ordering yet. Also, after discussion with Akos Toth, the additional headers that Acquia Dice does not use do not need an empty new line and hence can be removed from the canonicalized request.

### CODE REVIEW

**Comment by nickveenhof** [comment]
Details about the additional headers: https://github.com/acquia/http-hmac-spec/commit/8675b9dc0d9753657de71f5991c5ec37f6e38e03

**Comment by nickveenhof** [comment]
Ping @katbailey for review and @bryanholder for testing

**Comment by ynx** [comment]
@nickveenhof what's the status of this PR? Can we close it as outdated and delete hash-hmac-ordering-bug branch?

**Comment by scor** [comment]
This has become outdated.

**Pull request closed without merging**
