### PR TITLE
DIT-398 Add Acquia CI

### PR DESCRIPTION
**Pull request by mglaman**

### CODE REVIEW

**Comment by scor** [comment]
@mglaman we're deprecating this module in favor of https://github.com/acquia/acquia_perz

**Comment by mglaman** [comment]
@scor I know, I should have started there. But it's to hit an OKR (move one DIT module to Acquia CI) and this started, so 🤷‍♂️. I guess this could _technically_ need a hotfix and need CI runs

**Comment by scor** [comment]
sounds good thanks Matt!

**Comment by mglaman** [comment]
@scor wondering if you care to eyeball this. The fails on Acquia CI look similar to Travis. So we could make the cut over to Acquia CI. (Just looking for an Approve button if you think it looks good.)

**Comment by japerry** [comment]
I need to merge this so I can get some D10 tests working here. so looks good enough to me for now!

**Pull request merged**
