### PR TITLE
LEB-3179 | Make Decision API url required and set default to main production endpoint

### PR DESCRIPTION
**Pull request by scor**

### CODE REVIEW

**Review by baophan1 — APPROVED** [review]
Looks good! Is it necessary to add this as a unit test or is it overkill?

**Review by baophan1 — CHANGES_REQUESTED** [review]
Sorry I realize that if the url is localhost, the url is required to use `http` rather than `https`. We'll need to add an if statement to check for this

**Review by hzheng06 — APPROVED** [review]
LGTM!

**Comment by scor** [comment]
> Sorry I realize that if the url is localhost, the url is required to use `http` rather than `https`. We'll need to add an if statement to check for this

This URL is the Decision API endpoint URL, so it should always be https and never localhost.

**Comment by scor** [comment]
> Looks good! Is it necessary to add this as a unit test or is it overkill?

overkill IMO since we are using Drupal core Form API which is well tested in core itself.

**Review by baophan1 — APPROVED** [review]
I'm good with the changes if the assumption that localhost will never be used

**Pull request merged**
